routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SinhvienController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('/sinhvien', SinhvienController::class);
// Route::get('search_sinhvien/{id}',[SinhvienController::class,'search']);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/sinhvien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class sinhvien extends Model
{
    use HasFactory;
    protected $fillable = [
        'fullname','birthday','address'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SinhvienController.php
<?php

namespace App\Http\Controllers;

use App\Models\sinhvien;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;

class SinhvienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sinhvien = sinhvien::paginate(5); //fetch all products from DB
        return view('index', compact('sinhvien'))->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        sinhvien::create($request->all());
        return redirect()->route('sinhvien.index')->with('thongbao','them sinh vien thanh cong !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\sinhvien  $sinhvien
     * @return \Illuminate\Http\Response
     */
    public function search($id)
    {
        $sinhvien=DB::table('sinhviens')->where('id',$id)->get();
        return view('search',compact('sinhvien'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Sinhvien  $sinhvien
     * @return \Illuminate\Http\Response
     */
    public function edit(sinhvien $sinhvien)
    {
        return view('edit', compact('sinhvien'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Sinhvien  $sinhvien
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, sinhvien $sinhvien)
    {
        // $sinhvien->update([
        //     'fullname' => $request->fullname,
        //     'birthday' => $request->birthday,
        //     'address' => $request->address
        // ]);
        
        // return redirect('sinhvien.index' . $sinhvien->id . 'sinhvien.edit');
        $sinhvien->update($request->all());
        return redirect()->route('sinhvien.index')->with('thongbao','cap nhat thanh cong !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\sinhvien  $sinhvien
     * @return \Illuminate\Http\Response
     */
    public function destroy(sinhvien $sinhvien)
    {
        $sinhvien->delete();
        return redirect()->route('sinhvien.index')->with('thongbao','xoa thanh cong !');
    }
}

resources/views/create.blade.php
@extends('layout')
@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Thêm mới sinh viên</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('sinhvien.index')}}" class="btn btn-primary float-end">Danh sách sinh viên</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{route('sinhvien.store')}}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Full name</strong>
                                <input type="text" name="fullname" class="form-control" placeholder="nhập tên sinh viên">
                            </div>
                            <div class="form-group">
                                <strong>Birthday</strong>
                                <input type="date" name="birthday" class="form-control" placeholder="nhập ngày sinh">
                            </div>
                            <div class="form-group">
                                <strong>Address</strong>
                                <input type="text" name="address" class="form-control" placeholder="nhập địa chỉ">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Lưu</button>
                </form>               
            </div>
        </div>
    </div>
@endsection

resources/views/edit.blade.php
@extends('layout')
@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Sửa thông tin sinh viên</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('sinhvien.index')}}" class="btn btn-primary float-end">Danh sách sinh viên</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{route('sinhvien.update',$sinhvien->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Full name</strong>
                                <input type="text" name="fullname" value="{{$sinhvien->fullname}}" class="form-control" placeholder="nhập họ tên sinh viên">
                            </div>
                            <div class="form-group">
                                <strong>Birthday</strong>
                                <input type="date" name="birthday" value="{{$sinhvien->birthday}}" class="form-control" placeholder="nhập ngày sinh">
                            </div>
                            <div class="form-group">
                                <strong>Address</strong>
                                <input type="text" name="address" value="{{$sinhvien->address}}" class="form-control" placeholder="nhập địa chỉ">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Cập nhật</button>
                </form>               
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layout')
@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <h3>Quản lý sinh viên</h3>
                </div> 
                <div class="col-md-6">
                    <a href="{{route('sinhvien.create')}}" class="btn btn-primary float-end">Thêm mới</a>
                </div>
                {{-- <div class="col-md-6">
                    <a href="{{route('sinhvien.search')}}" class="btn btn-primary float-end">Tìm kiếm</a>
                </div> --}}
            </div>
        </div>
        <div class="card-body">
            @if (Session::has('thongbao'))
            <div class="alert alert-success">
                {{Session::get('thongbao')}}
            </div>             
            @endif
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Full Name</th>
                        <th>Birthday</th>
                        <th>Address</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($sinhvien as $sv)
                        <tr>
                            <td>{{++$i}}</td>
                            <td>{{$sv->fullname}}</td>
                            <td>{{$sv->birthday}}</td>
                            <td>{{$sv->address}}</td>
                            <td>
                                <form action="{{route('sinhvien.destroy',$sv->id)}}" method="POST" class="text-center">
                                    <a href="{{route('sinhvien.edit',$sv->id)}}" class="btn btn-info">Sửa</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Xóa</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Thêm ,sửa,xóa sinh viên</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    @yield('content')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

resources/views/search.blade.php
@extends('layout')
@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <h3>Thông tin sinh viên</h3>
                </div> 
                <div class="col-md-6">
                    <a href="{{route('sinhvien.create')}}" class="btn btn-primary float-end">Thêm mới</a>
                </div>          
            </div>
        </div>
        <div class="card-body">
            @if (Session::has('thongbao'))
            <div class="alert alert-success">
                {{Session::get('thongbao')}}
            </div>             
            @endif
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Full Name</th>
                        <th>Birthday</th>
                        <th>Address</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($sinhvien as $sv)
                        <tr>
                            <td>{{++$i}}</td>
                            <td>{{$sv->fullname}}</td>
                            <td>{{$sv->birthday}}</td>
                            <td>{{$sv->address}}</td>
                            <td>
                                <form action="{{route('sinhvien.destroy',$sv->id)}}" method="POST">
                                    <a href="{{route('sinhvien.edit',$sv->id)}}" class="btn btn-info">Sửa</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Xóa</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>